title: Humanities Without Walls Career Diversity Toolkit
description: Resources and information for graduate students intending to work outside academia
theme: just-the-docs

color_scheme: dark

logo: "/assets/images/site_logo.png"

url: https://hwwcareerdiversity.github.io

aux_links:
  Humanities Without Walls: https://www.humanitieswithoutwalls.illinois.edu/
